# Generated by Django 3.2.25 on 2024-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=20)),
                ('passwordcheck', models.TextField(max_length=20)),
            ],
        ),
    ]
