# Generated by Django 3.2.25 on 2024-03-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastroUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
